//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.19 at 07:09:03 PM CEST 
//


package biz.company.api;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom;
import org.jvnet.jaxb2_commons.lang.MergeStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for articleCategoryDTOList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="articleCategoryDTOList">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.company.biz}abstractList">
 *       &lt;sequence>
 *         &lt;element ref="{http://api.company.biz}articleCategory" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "articleCategoryDTOList", propOrder = {
    "articleCategory"
})
public class ArticleCategoryDTOList
    extends AbstractList
    implements Cloneable, CopyTo, Equals, HashCode, MergeFrom, ToString
{

    protected List<ArticleCategoryDTO> articleCategory;

    /**
     * Gets the value of the articleCategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articleCategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticleCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArticleCategoryDTO }
     * 
     * 
     */
    public List<ArticleCategoryDTO> getArticleCategory() {
        if (articleCategory == null) {
            articleCategory = new ArrayList<ArticleCategoryDTO>();
        }
        return this.articleCategory;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            List<ArticleCategoryDTO> theArticleCategory;
            theArticleCategory = (((this.articleCategory!= null)&&(!this.articleCategory.isEmpty()))?this.getArticleCategory():null);
            strategy.appendField(locator, this, "articleCategory", buffer, theArticleCategory);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ArticleCategoryDTOList)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final ArticleCategoryDTOList that = ((ArticleCategoryDTOList) object);
        {
            List<ArticleCategoryDTO> lhsArticleCategory;
            lhsArticleCategory = (((this.articleCategory!= null)&&(!this.articleCategory.isEmpty()))?this.getArticleCategory():null);
            List<ArticleCategoryDTO> rhsArticleCategory;
            rhsArticleCategory = (((that.articleCategory!= null)&&(!that.articleCategory.isEmpty()))?that.getArticleCategory():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "articleCategory", lhsArticleCategory), LocatorUtils.property(thatLocator, "articleCategory", rhsArticleCategory), lhsArticleCategory, rhsArticleCategory)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<ArticleCategoryDTO> theArticleCategory;
            theArticleCategory = (((this.articleCategory!= null)&&(!this.articleCategory.isEmpty()))?this.getArticleCategory():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "articleCategory", theArticleCategory), currentHashCode, theArticleCategory);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof ArticleCategoryDTOList) {
            final ArticleCategoryDTOList copy = ((ArticleCategoryDTOList) draftCopy);
            if ((this.articleCategory!= null)&&(!this.articleCategory.isEmpty())) {
                List<ArticleCategoryDTO> sourceArticleCategory;
                sourceArticleCategory = (((this.articleCategory!= null)&&(!this.articleCategory.isEmpty()))?this.getArticleCategory():null);
                @SuppressWarnings("unchecked")
                List<ArticleCategoryDTO> copyArticleCategory = ((List<ArticleCategoryDTO> ) strategy.copy(LocatorUtils.property(locator, "articleCategory", sourceArticleCategory), sourceArticleCategory));
                copy.articleCategory = null;
                if (copyArticleCategory!= null) {
                    List<ArticleCategoryDTO> uniqueArticleCategoryl = copy.getArticleCategory();
                    uniqueArticleCategoryl.addAll(copyArticleCategory);
                }
            } else {
                copy.articleCategory = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new ArticleCategoryDTOList();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy strategy) {
        super.mergeFrom(leftLocator, rightLocator, left, right, strategy);
        if (right instanceof ArticleCategoryDTOList) {
            final ArticleCategoryDTOList target = this;
            final ArticleCategoryDTOList leftObject = ((ArticleCategoryDTOList) left);
            final ArticleCategoryDTOList rightObject = ((ArticleCategoryDTOList) right);
            {
                List<ArticleCategoryDTO> lhsArticleCategory;
                lhsArticleCategory = (((leftObject.articleCategory!= null)&&(!leftObject.articleCategory.isEmpty()))?leftObject.getArticleCategory():null);
                List<ArticleCategoryDTO> rhsArticleCategory;
                rhsArticleCategory = (((rightObject.articleCategory!= null)&&(!rightObject.articleCategory.isEmpty()))?rightObject.getArticleCategory():null);
                List<ArticleCategoryDTO> mergedArticleCategory = ((List<ArticleCategoryDTO> ) strategy.merge(LocatorUtils.property(leftLocator, "articleCategory", lhsArticleCategory), LocatorUtils.property(rightLocator, "articleCategory", rhsArticleCategory), lhsArticleCategory, rhsArticleCategory));
                target.articleCategory = null;
                if (mergedArticleCategory!= null) {
                    List<ArticleCategoryDTO> uniqueArticleCategoryl = target.getArticleCategory();
                    uniqueArticleCategoryl.addAll(mergedArticleCategory);
                }
            }
        }
    }

    public ArticleCategoryDTOList withArticleCategory(ArticleCategoryDTO... values) {
        if (values!= null) {
            for (ArticleCategoryDTO value: values) {
                getArticleCategory().add(value);
            }
        }
        return this;
    }

    public ArticleCategoryDTOList withArticleCategory(Collection<ArticleCategoryDTO> values) {
        if (values!= null) {
            getArticleCategory().addAll(values);
        }
        return this;
    }

    @Override
    public ArticleCategoryDTOList withFacets(AbstractList.Facets value) {
        setFacets(value);
        return this;
    }

    @Override
    public ArticleCategoryDTOList withHref(String value) {
        setHref(value);
        return this;
    }

    @Override
    public ArticleCategoryDTOList withOffset(long value) {
        setOffset(value);
        return this;
    }

    @Override
    public ArticleCategoryDTOList withLimit(long value) {
        setLimit(value);
        return this;
    }

    @Override
    public ArticleCategoryDTOList withCount(long value) {
        setCount(value);
        return this;
    }

    @Override
    public ArticleCategoryDTOList withSortField(String value) {
        setSortField(value);
        return this;
    }

    @Override
    public ArticleCategoryDTOList withSortOrder(String value) {
        setSortOrder(value);
        return this;
    }

    @Override
    public ArticleCategoryDTOList withQuery(String value) {
        setQuery(value);
        return this;
    }

    @Override
    public ArticleCategoryDTOList withSuggestedQuery(String value) {
        setSuggestedQuery(value);
        return this;
    }

    @Override
    public ArticleCategoryDTOList withExecutedQuery(String value) {
        setExecutedQuery(value);
        return this;
    }

    @Override
    public ArticleCategoryDTOList withUngroupedCount(Long value) {
        setUngroupedCount(value);
        return this;
    }

}
