//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.19 at 07:09:03 PM CEST 
//


package biz.company.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom;
import org.jvnet.jaxb2_commons.lang.MergeStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for productTypeDefaultValuesDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productTypeDefaultValuesDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="defaultView" type="{http://api.company.biz}reference"/>
 *         &lt;element name="defaultAppearance" type="{http://api.company.biz}reference"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productTypeDefaultValuesDTO", propOrder = {
    "defaultView",
    "defaultAppearance"
})
public class ProductTypeDefaultValuesDTO
    implements Cloneable, CopyTo, Equals, HashCode, MergeFrom, ToString
{

    @XmlElement(required = true)
    protected Reference defaultView;
    @XmlElement(required = true)
    protected Reference defaultAppearance;

    /**
     * Gets the value of the defaultView property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getDefaultView() {
        return defaultView;
    }

    /**
     * Sets the value of the defaultView property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setDefaultView(Reference value) {
        this.defaultView = value;
    }

    /**
     * Gets the value of the defaultAppearance property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getDefaultAppearance() {
        return defaultAppearance;
    }

    /**
     * Sets the value of the defaultAppearance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setDefaultAppearance(Reference value) {
        this.defaultAppearance = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            Reference theDefaultView;
            theDefaultView = this.getDefaultView();
            strategy.appendField(locator, this, "defaultView", buffer, theDefaultView);
        }
        {
            Reference theDefaultAppearance;
            theDefaultAppearance = this.getDefaultAppearance();
            strategy.appendField(locator, this, "defaultAppearance", buffer, theDefaultAppearance);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ProductTypeDefaultValuesDTO)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ProductTypeDefaultValuesDTO that = ((ProductTypeDefaultValuesDTO) object);
        {
            Reference lhsDefaultView;
            lhsDefaultView = this.getDefaultView();
            Reference rhsDefaultView;
            rhsDefaultView = that.getDefaultView();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "defaultView", lhsDefaultView), LocatorUtils.property(thatLocator, "defaultView", rhsDefaultView), lhsDefaultView, rhsDefaultView)) {
                return false;
            }
        }
        {
            Reference lhsDefaultAppearance;
            lhsDefaultAppearance = this.getDefaultAppearance();
            Reference rhsDefaultAppearance;
            rhsDefaultAppearance = that.getDefaultAppearance();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "defaultAppearance", lhsDefaultAppearance), LocatorUtils.property(thatLocator, "defaultAppearance", rhsDefaultAppearance), lhsDefaultAppearance, rhsDefaultAppearance)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            Reference theDefaultView;
            theDefaultView = this.getDefaultView();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "defaultView", theDefaultView), currentHashCode, theDefaultView);
        }
        {
            Reference theDefaultAppearance;
            theDefaultAppearance = this.getDefaultAppearance();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "defaultAppearance", theDefaultAppearance), currentHashCode, theDefaultAppearance);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof ProductTypeDefaultValuesDTO) {
            final ProductTypeDefaultValuesDTO copy = ((ProductTypeDefaultValuesDTO) draftCopy);
            if (this.defaultView!= null) {
                Reference sourceDefaultView;
                sourceDefaultView = this.getDefaultView();
                Reference copyDefaultView = ((Reference) strategy.copy(LocatorUtils.property(locator, "defaultView", sourceDefaultView), sourceDefaultView));
                copy.setDefaultView(copyDefaultView);
            } else {
                copy.defaultView = null;
            }
            if (this.defaultAppearance!= null) {
                Reference sourceDefaultAppearance;
                sourceDefaultAppearance = this.getDefaultAppearance();
                Reference copyDefaultAppearance = ((Reference) strategy.copy(LocatorUtils.property(locator, "defaultAppearance", sourceDefaultAppearance), sourceDefaultAppearance));
                copy.setDefaultAppearance(copyDefaultAppearance);
            } else {
                copy.defaultAppearance = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new ProductTypeDefaultValuesDTO();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy strategy) {
        if (right instanceof ProductTypeDefaultValuesDTO) {
            final ProductTypeDefaultValuesDTO target = this;
            final ProductTypeDefaultValuesDTO leftObject = ((ProductTypeDefaultValuesDTO) left);
            final ProductTypeDefaultValuesDTO rightObject = ((ProductTypeDefaultValuesDTO) right);
            {
                Reference lhsDefaultView;
                lhsDefaultView = leftObject.getDefaultView();
                Reference rhsDefaultView;
                rhsDefaultView = rightObject.getDefaultView();
                Reference mergedDefaultView = ((Reference) strategy.merge(LocatorUtils.property(leftLocator, "defaultView", lhsDefaultView), LocatorUtils.property(rightLocator, "defaultView", rhsDefaultView), lhsDefaultView, rhsDefaultView));
                target.setDefaultView(mergedDefaultView);
            }
            {
                Reference lhsDefaultAppearance;
                lhsDefaultAppearance = leftObject.getDefaultAppearance();
                Reference rhsDefaultAppearance;
                rhsDefaultAppearance = rightObject.getDefaultAppearance();
                Reference mergedDefaultAppearance = ((Reference) strategy.merge(LocatorUtils.property(leftLocator, "defaultAppearance", lhsDefaultAppearance), LocatorUtils.property(rightLocator, "defaultAppearance", rhsDefaultAppearance), lhsDefaultAppearance, rhsDefaultAppearance));
                target.setDefaultAppearance(mergedDefaultAppearance);
            }
        }
    }

    public ProductTypeDefaultValuesDTO withDefaultView(Reference value) {
        setDefaultView(value);
        return this;
    }

    public ProductTypeDefaultValuesDTO withDefaultAppearance(Reference value) {
        setDefaultAppearance(value);
        return this;
    }

}
