//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.19 at 07:09:03 PM CEST 
//


package biz.company.api;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom;
import org.jvnet.jaxb2_commons.lang.MergeStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for basketItemDTOList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="basketItemDTOList">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.company.biz}abstractList">
 *       &lt;sequence>
 *         &lt;element ref="{http://api.company.biz}basketItem" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "basketItemDTOList", propOrder = {
    "basketItem"
})
public class BasketItemDTOList
    extends AbstractList
    implements Cloneable, CopyTo, Equals, HashCode, MergeFrom, ToString
{

    protected List<BasketItemDTO> basketItem;

    /**
     * Gets the value of the basketItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the basketItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBasketItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BasketItemDTO }
     * 
     * 
     */
    public List<BasketItemDTO> getBasketItem() {
        if (basketItem == null) {
            basketItem = new ArrayList<BasketItemDTO>();
        }
        return this.basketItem;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            List<BasketItemDTO> theBasketItem;
            theBasketItem = (((this.basketItem!= null)&&(!this.basketItem.isEmpty()))?this.getBasketItem():null);
            strategy.appendField(locator, this, "basketItem", buffer, theBasketItem);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof BasketItemDTOList)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final BasketItemDTOList that = ((BasketItemDTOList) object);
        {
            List<BasketItemDTO> lhsBasketItem;
            lhsBasketItem = (((this.basketItem!= null)&&(!this.basketItem.isEmpty()))?this.getBasketItem():null);
            List<BasketItemDTO> rhsBasketItem;
            rhsBasketItem = (((that.basketItem!= null)&&(!that.basketItem.isEmpty()))?that.getBasketItem():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "basketItem", lhsBasketItem), LocatorUtils.property(thatLocator, "basketItem", rhsBasketItem), lhsBasketItem, rhsBasketItem)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<BasketItemDTO> theBasketItem;
            theBasketItem = (((this.basketItem!= null)&&(!this.basketItem.isEmpty()))?this.getBasketItem():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "basketItem", theBasketItem), currentHashCode, theBasketItem);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof BasketItemDTOList) {
            final BasketItemDTOList copy = ((BasketItemDTOList) draftCopy);
            if ((this.basketItem!= null)&&(!this.basketItem.isEmpty())) {
                List<BasketItemDTO> sourceBasketItem;
                sourceBasketItem = (((this.basketItem!= null)&&(!this.basketItem.isEmpty()))?this.getBasketItem():null);
                @SuppressWarnings("unchecked")
                List<BasketItemDTO> copyBasketItem = ((List<BasketItemDTO> ) strategy.copy(LocatorUtils.property(locator, "basketItem", sourceBasketItem), sourceBasketItem));
                copy.basketItem = null;
                if (copyBasketItem!= null) {
                    List<BasketItemDTO> uniqueBasketIteml = copy.getBasketItem();
                    uniqueBasketIteml.addAll(copyBasketItem);
                }
            } else {
                copy.basketItem = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new BasketItemDTOList();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy strategy) {
        super.mergeFrom(leftLocator, rightLocator, left, right, strategy);
        if (right instanceof BasketItemDTOList) {
            final BasketItemDTOList target = this;
            final BasketItemDTOList leftObject = ((BasketItemDTOList) left);
            final BasketItemDTOList rightObject = ((BasketItemDTOList) right);
            {
                List<BasketItemDTO> lhsBasketItem;
                lhsBasketItem = (((leftObject.basketItem!= null)&&(!leftObject.basketItem.isEmpty()))?leftObject.getBasketItem():null);
                List<BasketItemDTO> rhsBasketItem;
                rhsBasketItem = (((rightObject.basketItem!= null)&&(!rightObject.basketItem.isEmpty()))?rightObject.getBasketItem():null);
                List<BasketItemDTO> mergedBasketItem = ((List<BasketItemDTO> ) strategy.merge(LocatorUtils.property(leftLocator, "basketItem", lhsBasketItem), LocatorUtils.property(rightLocator, "basketItem", rhsBasketItem), lhsBasketItem, rhsBasketItem));
                target.basketItem = null;
                if (mergedBasketItem!= null) {
                    List<BasketItemDTO> uniqueBasketIteml = target.getBasketItem();
                    uniqueBasketIteml.addAll(mergedBasketItem);
                }
            }
        }
    }

    public BasketItemDTOList withBasketItem(BasketItemDTO... values) {
        if (values!= null) {
            for (BasketItemDTO value: values) {
                getBasketItem().add(value);
            }
        }
        return this;
    }

    public BasketItemDTOList withBasketItem(Collection<BasketItemDTO> values) {
        if (values!= null) {
            getBasketItem().addAll(values);
        }
        return this;
    }

    @Override
    public BasketItemDTOList withFacets(AbstractList.Facets value) {
        setFacets(value);
        return this;
    }

    @Override
    public BasketItemDTOList withHref(String value) {
        setHref(value);
        return this;
    }

    @Override
    public BasketItemDTOList withOffset(long value) {
        setOffset(value);
        return this;
    }

    @Override
    public BasketItemDTOList withLimit(long value) {
        setLimit(value);
        return this;
    }

    @Override
    public BasketItemDTOList withCount(long value) {
        setCount(value);
        return this;
    }

    @Override
    public BasketItemDTOList withSortField(String value) {
        setSortField(value);
        return this;
    }

    @Override
    public BasketItemDTOList withSortOrder(String value) {
        setSortOrder(value);
        return this;
    }

    @Override
    public BasketItemDTOList withQuery(String value) {
        setQuery(value);
        return this;
    }

    @Override
    public BasketItemDTOList withSuggestedQuery(String value) {
        setSuggestedQuery(value);
        return this;
    }

    @Override
    public BasketItemDTOList withExecutedQuery(String value) {
        setExecutedQuery(value);
        return this;
    }

    @Override
    public BasketItemDTOList withUngroupedCount(Long value) {
        setUngroupedCount(value);
        return this;
    }

}
