//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.19 at 07:09:03 PM CEST 
//


package biz.company.api;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom;
import org.jvnet.jaxb2_commons.lang.MergeStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for productTypeSizeDTOList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productTypeSizeDTOList">
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.company.biz}abstractList">
 *       &lt;sequence>
 *         &lt;element ref="{http://api.company.biz}size" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productTypeSizeDTOList", propOrder = {
    "size"
})
public class ProductTypeSizeDTOList
    extends AbstractList
    implements Cloneable, CopyTo, Equals, HashCode, MergeFrom, ToString
{

    protected List<ProductTypeSizeDTO> size;

    /**
     * Gets the value of the size property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the size property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSize().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductTypeSizeDTO }
     * 
     * 
     */
    public List<ProductTypeSizeDTO> getSize() {
        if (size == null) {
            size = new ArrayList<ProductTypeSizeDTO>();
        }
        return this.size;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            List<ProductTypeSizeDTO> theSize;
            theSize = (((this.size!= null)&&(!this.size.isEmpty()))?this.getSize():null);
            strategy.appendField(locator, this, "size", buffer, theSize);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ProductTypeSizeDTOList)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final ProductTypeSizeDTOList that = ((ProductTypeSizeDTOList) object);
        {
            List<ProductTypeSizeDTO> lhsSize;
            lhsSize = (((this.size!= null)&&(!this.size.isEmpty()))?this.getSize():null);
            List<ProductTypeSizeDTO> rhsSize;
            rhsSize = (((that.size!= null)&&(!that.size.isEmpty()))?that.getSize():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "size", lhsSize), LocatorUtils.property(thatLocator, "size", rhsSize), lhsSize, rhsSize)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<ProductTypeSizeDTO> theSize;
            theSize = (((this.size!= null)&&(!this.size.isEmpty()))?this.getSize():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "size", theSize), currentHashCode, theSize);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof ProductTypeSizeDTOList) {
            final ProductTypeSizeDTOList copy = ((ProductTypeSizeDTOList) draftCopy);
            if ((this.size!= null)&&(!this.size.isEmpty())) {
                List<ProductTypeSizeDTO> sourceSize;
                sourceSize = (((this.size!= null)&&(!this.size.isEmpty()))?this.getSize():null);
                @SuppressWarnings("unchecked")
                List<ProductTypeSizeDTO> copySize = ((List<ProductTypeSizeDTO> ) strategy.copy(LocatorUtils.property(locator, "size", sourceSize), sourceSize));
                copy.size = null;
                if (copySize!= null) {
                    List<ProductTypeSizeDTO> uniqueSizel = copy.getSize();
                    uniqueSizel.addAll(copySize);
                }
            } else {
                copy.size = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new ProductTypeSizeDTOList();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy strategy) {
        super.mergeFrom(leftLocator, rightLocator, left, right, strategy);
        if (right instanceof ProductTypeSizeDTOList) {
            final ProductTypeSizeDTOList target = this;
            final ProductTypeSizeDTOList leftObject = ((ProductTypeSizeDTOList) left);
            final ProductTypeSizeDTOList rightObject = ((ProductTypeSizeDTOList) right);
            {
                List<ProductTypeSizeDTO> lhsSize;
                lhsSize = (((leftObject.size!= null)&&(!leftObject.size.isEmpty()))?leftObject.getSize():null);
                List<ProductTypeSizeDTO> rhsSize;
                rhsSize = (((rightObject.size!= null)&&(!rightObject.size.isEmpty()))?rightObject.getSize():null);
                List<ProductTypeSizeDTO> mergedSize = ((List<ProductTypeSizeDTO> ) strategy.merge(LocatorUtils.property(leftLocator, "size", lhsSize), LocatorUtils.property(rightLocator, "size", rhsSize), lhsSize, rhsSize));
                target.size = null;
                if (mergedSize!= null) {
                    List<ProductTypeSizeDTO> uniqueSizel = target.getSize();
                    uniqueSizel.addAll(mergedSize);
                }
            }
        }
    }

    public ProductTypeSizeDTOList withSize(ProductTypeSizeDTO... values) {
        if (values!= null) {
            for (ProductTypeSizeDTO value: values) {
                getSize().add(value);
            }
        }
        return this;
    }

    public ProductTypeSizeDTOList withSize(Collection<ProductTypeSizeDTO> values) {
        if (values!= null) {
            getSize().addAll(values);
        }
        return this;
    }

    @Override
    public ProductTypeSizeDTOList withFacets(AbstractList.Facets value) {
        setFacets(value);
        return this;
    }

    @Override
    public ProductTypeSizeDTOList withHref(String value) {
        setHref(value);
        return this;
    }

    @Override
    public ProductTypeSizeDTOList withOffset(long value) {
        setOffset(value);
        return this;
    }

    @Override
    public ProductTypeSizeDTOList withLimit(long value) {
        setLimit(value);
        return this;
    }

    @Override
    public ProductTypeSizeDTOList withCount(long value) {
        setCount(value);
        return this;
    }

    @Override
    public ProductTypeSizeDTOList withSortField(String value) {
        setSortField(value);
        return this;
    }

    @Override
    public ProductTypeSizeDTOList withSortOrder(String value) {
        setSortOrder(value);
        return this;
    }

    @Override
    public ProductTypeSizeDTOList withQuery(String value) {
        setQuery(value);
        return this;
    }

    @Override
    public ProductTypeSizeDTOList withSuggestedQuery(String value) {
        setSuggestedQuery(value);
        return this;
    }

    @Override
    public ProductTypeSizeDTOList withExecutedQuery(String value) {
        setExecutedQuery(value);
        return this;
    }

    @Override
    public ProductTypeSizeDTOList withUngroupedCount(Long value) {
        setUngroupedCount(value);
        return this;
    }

}
